pub mod collapsable_wave_function;
pub mod sequential_collapsable_wave_function;
pub mod sequential_adjacent_collapsable_wave_function;
pub mod accommodating_collapsable_wave_function;
pub mod accommodating_sequential_collapsable_wave_function;
pub mod entropic_collapsable_wave_function;